# Generated by Django 2.2.11 on 2020-04-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200407_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='desire',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'ordering': ['id']},
        ),
    ]
